### PR TITLE
PUBD-298,319 Update EZID Plugin to work with 1.4.x

### PR DESCRIPTION
**Pull request by hardyoyo**
- Revamp the plugin_settings file to match what Janeway 1.4.x expects
- Handle null authors by looking for an account if the author object is null

### CODE REVIEW

**Comment by hardyoyo** [comment]
Installs without complaint on the dev server. Needs testing to confirm the plugin still works.

**Review by tingletech — APPROVED** [review]

**Comment by hardyoyo** [comment]
whoops, a syntax error, on it

**Comment by hardyoyo** [comment]
the management/CLI commands seem to be working correctly on dev, still need to submit and accept a test preprint

**Comment by hardyoyo** [comment]
An error during tesing:

```
  File "/apps/eschol/janeway/src/plugins/ezid/logic.py", line 240, in preprint_publication
    def preprint_publication(**kwargs):
AttributeError: 'NoneType' object has no attribute 'url'
```

It would seem that the preprint object may not be obtainable via kwargs in 1.4.x?

**Comment by hardyoyo** [comment]
It turns out that the error we observed in testing was due to a small bug in Janeway, which was fixed with this commit: https://github.com/BirkbeckCTP/janeway/commit/26767d0905cdc3f53997841f50e48c32b97bcf75

I'll do another test to confirm things are working.

**Comment by hardyoyo** [comment]
testing on dev.eartharxiv.org confirms this code is working
